### ISSUE TITLE
Kurnous Bow validation error on Farseer Skyrunner

### ISSUE THREAD

**Issue by StokerGamer** [BSData/wh40k-9e#11126]
**Describe the bug**
Farseer skyrunners get a validation error when the relic kurnous' bow is selected saying the farseer skyrunner has too many shuriken pistol selections. If you deselect the shuriken pisto option you get a validation error saying you need they cannot have kurnous' bow. 
**To Reproduce**
1. Add a 'Farseer Skyrunner'.
2. Select a warlord or add  'Stratagem: Treasures of the Aeldari' (doesn't matter wich character is your warlord) 
3. Add Relic 'Kurnous' Bow' to the 'Farseer Skyrunner' 
4. Get Validation Error

**Expected behavior**
The shuriken pistol should be mandatory not an option, Kurnous' Bow shouldnt give you any validation errors when taking it on the Farseer Skyrunner.

**Device and data (please complete the following information):**
 - OS: [Windows 10]
 - BattleScribe version [2.03.21]
 - Release version [v9.3.10]

**Comment by FarseerVeraenthis** [comment]
This is fixed already, please update your data, ensure that you delete existing data first :-)

**Comment by StokerGamer** [comment]
Sorry to bother you with this still, but its still happening. I tried updating the data, and checking the box to delete it, still was there, tried manually deleting the data and re downloading it and it didnt work. Lastly I tried importing the Aeldari .cat files from the master branch and it was still there. Also every time i tested it i created a new roster so it isnt that im loading a previous one.

![image](https://user-images.githubusercontent.com/11701471/162589690-30d37d19-00f7-4fe4-a25f-5eaa0dcb4741.png)

**Comment by FarseerVeraenthis** [comment]
![Screenshot_20220409-210119](https://user-images.githubusercontent.com/23246922/162589863-6d980263-e7a8-4653-9a27-f1fbbd5f0e37.png)

**Comment by FarseerVeraenthis** [comment]
You're right, the SKYRUNNER is still bugged... sorry, I missed that and only tested with the Farseer on foot :-)

**Comment by FarseerVeraenthis** [comment]
fix will be in the next release. the Skyrunner will now behave in the same way as the Farseer on foot :-)

**Comment by StokerGamer** [comment]
Thank you very much. :)
