### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11342]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Hello why is the app auto adding phoenix [legends] to every detachment? Even the super heavy aux gets it but since it has no flyer slot visible i cant remove it and i keep getting list error for not setting up the unit correctly

**Comment by Maycano** [comment]
Wasn’t logged in when reporting but i would like to be up to date

**Comment by FarseerVeraenthis** [comment]
Please update your data, this should be fixed already:+1:

**Comment by Maycano** [comment]
Still is not resolved still get the error after updating and even removing and adding the superheavy aux

**Comment by FarseerVeraenthis** [comment]
It is resolved in datafile version v157, please confirm you are using this version of the data.

**Comment by Maycano** [comment]
I confirm that the issue has been resolved!

Met vriendelijke groet,

Maikel Wierds

Bloemendaalstraat 7
7545SJ Enschede

Tel.: 0629011913
