### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11407]
**File:** Chaos - Chaos Knights.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When adding a dreadblade to a csm list in a Super-heavy Auxiliary detachment,  the infernal household daemonic surge table appears in the unit's profile page by default, even if you select an iconoclast household. Also the infernal household rules appear at the bottom whether you selected infernal or iconoclast. Not a huge issue but could be confusing for some. Thanks!

**Comment by Mad-Spy** [comment]
Fixed in current release (v71). Update your data.

**Comment by goosehammer** [comment]
I have version 71. Still shows up. In this case, its a cerastus lancer.

![Screenshot_20220620-193546](https://user-images.githubusercontent.com/82432174/174689198-b2768064-51e8-4db2-a17c-31c3f02be96e.jpg)

**Comment by Mad-Spy** [comment]
Yeah. The issue was specifically with the Lancer; all the others were working correctly. Fixed in v72 when it's released.

**Comment by goosehammer** [comment]
Dope. You guys are the best!
