### ISSUE TITLE
Imperium-Adeptus Astartes wrong pts value of Scout sniper rifle

### ISSUE THREAD

**Issue by Dzejra** [BSData/wh40k-9e#11684]
Imperium-Adeptus astartes-Ultramarines v.63 Scout squad.  Bad point value for wargear Scout sniper rifle.  Correct is 0 pts. It is stated In MUNITORUM FIELD MANUAL 2022 MK II there is a sentence: “weapons and other wargear not listed in a unit’s entry cost no additional points to include in that unit”

Device and data:
 - OS: iOS 15.5
 - BattleScribe version 2.03.15

**Comment by acebaur** [comment]
this is already fixed. Please update your data

**Comment by Dzejra** [comment]
I upgraded my data to the latest version and the bug is still there.
