### ISSUE TITLE
[Dark Angels] [Ancient in Terminatour Armour] Wrong cost for Thunder Hammer and Storm Shield option

### ISSUE THREAD

**Issue by NickTheSecond** [BSData/wh40k-9e#12198]
Data version v9.7.0
Dark Angels v255

Ancient in Terminator Armour (Deathwing Ancient) has weapons option for Thunder Hammer and Storm Shield listed for 20pts.
It should be free as per latest points update.

TY.

**Comment by AbonShell** [comment]
Fixed in next release

**Comment by NickTheSecond** [comment]
@AbonShell 
Issue is still present in 9.7.2.
I'm afraid I have to reopen it
