### ISSUE TITLE
Deathwing Ancient - Thunder Hammer & Storm Shield not free

### ISSUE THREAD

**Issue by DAN38100** [BSData/wh40k-9e#12192]
**Describe the bug**
The Deathwing Acient's TH/SS should be free now, but it still costs 20 points on Battlescribe.

**To Reproduce**
1. Go to Imperium - Adeptus Astartes - Dark Angels
2. Click on Elites and take the Deathwing Ancient (Ancient in Terminator Armor), or take a Deathwing Command Squad to be able to take the Deathwing Ancient in a "No Force Org Slot"
3. Scroll down to Thunder Hammer & Storm Shield
4. See that the Loadout still costs 20p

**Expected behavior**
The wargear should be free now.

**Screenshots**
-

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.21.166]
 - Release version [e.g. v9.7.0]

**Additional context**
-

**Comment by AbonShell** [comment]
Fixed in next release

**Comment by DAN38100** [comment]
Unfortunately, the problem still exists.

BattleScribe version 2.03.21.166
Release version v9.7.2
