### ISSUE TITLE
Chaos Daemons - Bloodthirster profiles

### ISSUE THREAD

**Issue by Cheexsta** [BSData/wh40k-9e#315]
**File/Catalogue:** Chaos Daemons v3

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** Yes

**Description:** Bloodthirster profiles all have some errors:
All: "Damage" profiles have the wrong entries in the "Remaining W" column. For example, a Bloodthirster  of Insensate Rage on full W should have M12", WS2+ and A6. Currently a BoIR shows M6", WS4+ and A2.

Unfettered Fury and Wrath of Khorne should have a depreciating BS value, not WS value. Insensate Rage is the only one with a depreciating WS value.

**Comment by cartag** [comment]
Fixed in CD v4.

**Comment by BriB23** [comment]
This issue has not been fixed. It's still incorrect in v7. Bloodthirster of Unfettered Fury and Wrath of Khorne Bloodthirster are still listed as having a depreciating WS values as they lose wounds. It should be the BS value.
