### ISSUE TITLE
Craftworlds Hornets still not working as intended

### ISSUE THREAD

**Issue by enhanced94** [BSData/wh40k-9e#9069]
**File/Catalogue:** Craftworlds

**BattleScribe version:** 2.03.21

**Platform:** All

**Dropbox:**

**Description:** The Craftworlds Hornets now correctly let you pick other heavy weapon options, but it will force to pick a shuriken cannon and if you don't, it will give u validation error. 
How it should be: baseline weapon is 2x shuriken cannon (as from the latest imperial armour compendium FAQs), that you can swap out to 2x of another heavy weapon.
Also, the hornet pulse laser has a new profile, it should now be Heavy 2, S7, Vp-2, D2

**Comment by FarseerVeraenthis** [comment]
Yup, so the first part of the problem is because I goofed up the update. It is fixed in the next release.
The second I will have to check but I imagine it is fixed on the next release anyway :-)

**Comment by enhanced94** [comment]
All good, ty for your work

**Comment by StudioNirin** [comment]
Just to say, the weapon options now work as intended, but the hornet pulse laser profile is still incorrect.

**Comment by enhanced94** [comment]
@FarseerVeraenthis As nirurin just said, unfortunately the Hornet Pulse Laser profile is still the old one.
